### ISSUE TITLE
What should the links do?

### ISSUE THREAD

**Issue by philholden** [KeywordBrain/redbox-react#10]
I notice errors are links e.g.

`webpack:///./src/components/Pane.js?:186:56 `

Clicking the link does nothing. How do I make the link do something interesting like display that line in context in editor or browser.

**Comment by gaearon** [comment]
I don't think Browsers have API for this. The “links” just roughly give you an idea of where source file is.

**Comment by mxlje** [comment]
We could look into changing the links so that they open an editor with the file at that specific line, if the URL scheme is registered. [Better Errors](https://github.com/charliesome/better_errors) for example does this for Rack Apps.

https://github.com/dhoulb/subl for example allows to set up a `subl://` URL handler for Sublime Text and I’m sure this could be done for other editors as well.

**Comment by davidpfahler** [comment]
As @mxlje said, the idea was to change this at some point in the future to open the line of code somewhere. My original intent was to open them in the chrome dev tools, but maybe we can come up with a better idea.

**Comment by gaearon** [comment]
I think opening in the editor would be awesome. FYI, starting with `react-transform-catch-errors@0.1.3`, the error component also receives `filename`. This means you can use it regardless of whether the user has source maps enabled, and it's guaranteed to be the absolute file name (although of course you only get it for the component whose `render` failed—not for any other item in the stack trace).

**Comment by trueter** [comment]
FYI [Jetbrains IDEs also support URL handlers with little configuration](https://devnet.jetbrains.com/message/5477503). 

Jetbrains and Sublime allow to specify line numbers. Maybe we could also pass them down to the `<ErrorReporter />`, @gaearon?
