### ISSUE TITLE
react-transform-catch-errors and webpack-dev-server

### ISSUE THREAD

**Issue by kevinrenskers** [KeywordBrain/redbox-react#36]
I made redbox-react work using the method from [react-transform-boilerplate](https://github.com/gaearon/react-transform-boilerplate), very similar to [your example](https://github.com/KeywordBrain/redbox-react/tree/master/examples/react-transform-catch-errors).

Then I tried to make it work using webpack-dev-server (still using babel-plugin-react-transform and react-transform-catch-errors). While hot reloading works fine, catching the errors and showing them with redbox-react does not.

I have no idea if this is an issue with redbox-react or with react-transform-catch-errors not actually catching any errors or not giving them to redbox-react or something? Does this actually depend on webpack-hot-middleware to work?

I have an example project here: https://github.com/kevinrenskers/react-transform-webpack-dev-server. I was hoping that maybe you could take a look and see what's wrong with this approach. Of course it works fine when I don't use webpack-dev-server but instead use express and webpack-hot-middleware and all that, but it feels a bit complicated to me, a lot of moving parts and dependancies. Using just webpack-dev-server, configured from the webpack config file, saves some dependancies and an external devServer.js file.

**Comment by richardscarrott** [comment]
@kevinrenskers did you ever find a solution to this as I've ran into the same problem -- works fine using `webpack-hot-middleware` but not with `webpack-dev-server`?

**Comment by kevinrenskers** [comment]
Nope :(

**Comment by stton** [comment]
I've also been trying to get this to work without webpack-hot-middleware but running into the same issue. I am able to get hot reload with webpack-dev-server using react-transform-hmr but no luck with react-transform-catch-errors.

**Comment by clouddra** [comment]
observed the same issue as well :(

**Comment by manV** [comment]
I am also having the same issue, doesn't work with webpack-dev-server

**Comment by gaearon** [comment]
I tried [this project](https://github.com/kevinrenskers/react-transform-webpack-dev-server) and it works just fine. **I think there may be confusion as to what is handled by react-transform-catch-errors, and what is not.**

## Errors handled by React Transform Catch Errors

* Runtime errors inside `render()` method or methods it calls

## Errors handled only by Webpack Hot Middleware

* Syntax errors

That's it! **So if you mistype `props` as `shprops` in your `render()` method, react-transform-catch-errors will catch it, but it is not able to catch syntax errors or runtime errors outside `render()`.**

The syntax errors won't be caught with WebpackDevServer because it's Webpack Hot Middleware that catches them. And the overlay it displays is different from (and unrelated to) redbox-react.

Hope it helps!
