### ISSUE TITLE
Add ability to render without being full-screen

### ISSUE THREAD

**Issue by glenjamin** [KeywordBrain/redbox-react#44]
I'd like to capture all errors and display them in the context of the component that failed - but it'd still like to use redbox, as the work that's gone into the display stuff is great.

Would you take a PR for this? It'd be another option that would skip the `position` styles and probably just apply `overflow:auto` instead.

**Comment by davidpfahler** [comment]
@glenjamin Thank you for this issue and the way you present your suggestion. I really appreciate it.

To your point: I know @gaearon has [voiced his opinion](https://github.com/KeywordBrain/redbox-react/issues/32#issuecomment-168100980) on changes like this that change the nature of this project. His point is – and, Dan, please correct me if I'm misrepresenting your opinion here – that redbox is an opinionated component and if you want something else you need to use a different component. It is true that I created this component because I missed the react-native dev experience when developing with react on the web. Thus, I wanted *an exact replica* of the redbox in react-native. I was also dreaming of a solution that would one day work on both platforms in the back of my head. In this sense, I agree with Dan.

Now then, we have to consider your argument as well. I agree with your point that repeating the work that has gone into the presentation of the error (i.e. replicating the react-native redbox) is not a good solution to your problem. We should also consider that the react-native way (i.e. covering the entire screen when one component fails) might not be the best solution, especially not on other form factors.

I would thus invite everyone to discuss what the best solution to these different use cases or – one might say – aesthetic choices of error reporting is. I think we can agree that we want to avoid a bloated `redbox-react` project that becomes unmaintainable. But we also don't want to reinvent the wheel. So, an ideal solution would probably involve a presentation layer that can be used in both (or multiple?) contexts. 

Theoretically, this should not be too hard to achieve, because redbox, right now, is really only a component that takes an error as input. It has no opinion on where the error comes from, who caught it or if somewhere else other errors are caught or presented. With some styling changes, confining redboxes to the boundaries of parent components should be doable. I can even imagine clicking (or tapping) on an error that is confined by its parent component and then expanding the error to the full screen (and minimizing it upon another click/tap). Then, this becomes an exercise of how this whole affair is configured without bloating the project.

As easy as it might sound at first, I think this has no easy solution (although, maybe, a simple one). I right now don't have the time, nor, honestly, the ambition to tackle this, but I would not be opposed to a pull request. If, however, the PR fails to achieve the goals laid out above and bloats the project, I will veto a merge.

I should also mention @mik01aj here, because he was raising a similar issue on #32.

**Comment by glenjamin** [comment]
Thanks for the well though out response.

I think there's two useful actions to take away from this in the short term

1) Link to some other decent components for error display in the docs
    * The best way to remain opinionated is to direct people elsewhere when they differ
    * redbox is probably the most commonly used, so is the one that comes up in searches

2) I'll have a quick go at a PR to see how intrusive a change like this might be.

**Comment by glenjamin** [comment]
Ah, so while trying this out I've found that the following changes render reasonably inline in my case

```diff
-    position: 'fixed',
+    maxHeight: 400,
+    overflow: 'auto',
+    border: '3px solid red',
```

I've also found out about the style prop, so there's no need for a PR (although being able to deeply merge styles might be nice).

Would be good to get the styles prop in the docs though :)

**Comment by davidpfahler** [comment]
@glenjamin Would it be too much to ask for a PR including the mentioned doc changes?

**Comment by glenjamin** [comment]
Not at all, it's on my list now :)
