### ISSUE TITLE
please publish update to npm

### ISSUE THREAD

**Issue by rkstar** [KeywordBrain/redbox-react#50]
i'm trying to use react 15.0.0-rc2 but can't use redbox with it because [this update](https://github.com/KeywordBrain/redbox-react/commit/33704f7871152608f91d2e8c492f0893805006fa) from 15 days ago hasn't been published to npm.

**Comment by davidpfahler** [comment]
@rkstar Hi and thanks for opening this issue. Because this project is being released using [semantic-release](https://github.com/semantic-release/semantic-release), the commit you referenced was not automatically release, as `chore` commits are by definition not release worthy. I made an empty `fix` commit to get these changes out to npm. Should be fixed now. Please let me know if not.
